### ISSUE TITLE
listFiles in gulp-utils

### ISSUE THREAD

**Issue by willemneal** [near/near-shell#102]
Currently in `gulp-utils.js`, the `listFiles` function passed to `asc.main` is `listFiles: () => []`.  Previously this function was only used if you provided a library argument.  However, now with the module resolution it's used to determine if a folder is valid.  e.g.`../z/v/node_modules`.  Is there a reason for this?  Otherwise I'll remove it in the PR.
`

**Comment by vgrichina** [comment]
A reason for what, returning empty list? It should be possible to return real list as long as it's also patched on NEAR Studio side.
