### ISSUE TITLE
Key management improvements: current usage of neardev is confusing

### ISSUE THREAD

**Issue by janedegtiareva** [near/near-shell#198]
Stakewars feedback: 
nearshell always creates a folder of configuration named "neardev" on current directory after running "near login" command , when running nearshell on another folder without "neardev" folder, nearshell's login state would change to unlog, which would cause users to be confused .

Proposed solution is to store keys under .near (with the exception of development projects that keep their keys under neardev).

**Comment by kcole16** [comment]
@janedegtiareva Can this issue be closed?
