### ISSUE TITLE
Compilation without gulp

### ISSUE THREAD

**Issue by ColinEberhardt** [near/near-shell#205]
All of the NEAR demos use Gulp as part of the build process, however, the gulpfile tends to be pretty much trivial:

e.g. from https://github.com/nearprotocol/near-hello/blob/master/gulpfile.js

~~~
const gulp = require("gulp");
const nearUtils = require("near-shell/gulp-utils");

function build_wasm(done){
  nearUtils.compile("./assembly/main.ts", "./dist/main.wasm", done);
};

const build = gulp.series(build_wasm);

exports.default = build;
~~~ 

In my own projects, I just build via the following 2-line script, which means I don't have any dependency on Gulp (i.e. less stuff to install):

~~~
const nearUtils = require("near-shell/gulp-utils");
nearUtils.compile("./assembly/main.ts", "./out/main.wasm", () => {});
~~~

Is it worth making this a 'first class' feature of near shell?

Or, perhaps exposing this directly via the CLI ...

~~~
$ near compile ./assembly/main.ts -o ./out/main.wasm
~~~

**Comment by ColinEberhardt** [comment]
Actually - I think the `compile` function should live in a separate project, with both a JS API (as above) and a CLI interface. Just my 2 cents!

**Comment by bowenwang1996** [comment]
We use gulp due to legacy reasons -- when assemblyscript does not support package management we have to manually wrangle some path during the compilation process. But yeah good point we should reconsider this @vgrichina

**Comment by vgrichina** [comment]
Note that it’s expected that real life projects will have far more than 1 contract compiled.

**Comment by ColinEberhardt** [comment]
> Note that it’s expected that real life projects will have far more than 1 contract compiled.

Good point, although Gulp does look like it is on its way out ;-)

**Comment by mikedotexe** [comment]
Getting back to this issue. We have removed the gulp dependency. The next step is to get rid of `near build` and assuming that will run `gulp`
