### ISSUE TITLE
Delete account does not work

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-shell#221]
It seems that one can only send a delete account transaction from the account that you want to delete.

**Comment by janedegtiareva** [comment]
What's the use case for deleting a different account? It looks like this is a security feature not a bug.

**Comment by bowenwang1996** [comment]
The account system is designed such that when the balance of an account is below a certain threshold, anyone can delete the account and be rewarded with the remaining balance of that account.

**Comment by janedegtiareva** [comment]
Why do we want this? Is there some other mechanism to clean up the accounts?

**Comment by bowenwang1996** [comment]
No. That's the only way. Of course you can call this from smart contract but it is essentially the same thing.

**Comment by amgando** [comment]
closing since this seems to work from any account authorized to sign a transaction deleting an account, like an account that has a shorter account name: `contract.bob.testnet` can be deleted by `bob.testnet`
