### ISSUE TITLE
Show examples of args formatting for "call" and "view" commands

### ISSUE THREAD

**Issue by kcole16** [near/near-shell#237]
The current `--help` examples for `call` and `view` are unclear re:  how to format args. Additionally, they should specify that the `--accountId` flag is required.

```
  near call <contractName> <methodName> [args]  schedule smart contract call which can modify state
  near view <contractName> <methodName> [args]  make smart contract call which can view state
```

Attempts to use `[test]`, `['test']`, `["test"]`, etc all returned an error.

`near call studio-g2dknmak9 addMessage [test] --accountId <accountId>`

**Comment by vgrichina** [comment]
re: having `--accountId` flag as required – I kinda feel that we should either make it optional and instead remember account selected during `near login` and use it as default. Or we should restructure our commands around the fact that they always require account and have something like this `near calling_account_id call contract_name method_name`

as for args examples – it is contract-specific what can be accepted (in-theory any arbitrary blob). But we probably can show example of calling some of our sample contracts (like counter).
