### ISSUE TITLE
near login has an error

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-shell#242]
@wetezos commented on [Fri Dec 13 2019](https://github.com/nearprotocol/nearcore/issues/1860)

near version:near-shell@0.16.0

login error:

Please enter the accountId that you logged in with:wetez
Error: Querying access_key/wetez/ed25519:6HfPNi9CCv3a2cEbskxwsWAuSGVxLknsDzYn2CF7hW4u failed: access key ed25519:6HfPNi9CCv3a2cEbskxwsWAuSGVxLknsDzYn2CF7hW4u does not exist while viewing.
{
  "block_height": 102120,
  "error": "access key ed25519:6HfPNi9CCv3a2cEbskxwsWAuSGVxLknsDzYn2CF7hW4u does not exist while viewing",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-shell/node_modules/nearlib/lib/providers/json-rpc-provider.js:40:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by janedegtiareva** [comment]
We might want to bring this back as a lower priority item to enhance usability in this case ( I think this happens if there is something wrong that went with the adding key txn on the wallet side)
