### ISSUE TITLE
Generate project from template with a given contract name

### ISSUE THREAD

**Issue by vgrichina** [near/near-shell#25]
Generated template would generally have unique contract name, I'm thinking of following workflow.

Create app in `my-awesome-app` folder with `my-awesome-app` contract name:

```
npx create-near-app my-awesome-app
```

`npm install` done behind the scenes (like with `create-react-app`), contract account also created immediately.
This should also eventually have option for different stater templates, etc. 

Run generated app:

```
cd my-awesome-app
npm start
```

_Originally posted by @vgrichina in https://github.com/nearprotocol/near-shell/pull/24/files_

**Comment by janedegtiareva** [comment]
can we close this now?

**Comment by janedegtiareva** [comment]
Closing as old and out of date.
