### ISSUE TITLE
UX feedback: add a --verbose flag so that noisy logs are hidden by default

### ISSUE THREAD

**Issue by janedegtiareva** [near/near-shell#255]
@amgando if you still have that PR let's resurrect it and get it in! This would be a good improvement.

**Comment by vgrichina** [comment]
Feel like we actually aren't verbose enough by default. Like it's good to know where keys are written, etc. I'm not against `--silent` flag though. I'd expect `--verbose` to be far more detailed though, like maybe even logging HTTP requests, etc

It might make sense to add more detailed logging everywhere (I mean including nearlib) using https://www.npmjs.com/package/debug and then turn specific level, etc depending on flags passed.

**Comment by janedegtiareva** [comment]
Fixed by https://github.com/near/near-shell/pull/440
