### ISSUE TITLE
Deploying contracts with init methods is impossible

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-shell#260]
Given a contract that must be initializes on deployment, e.g. deploy + functionCall must be issued in the same transaction.

Also similar for contracts that not suppose to have access keys, e.g. createAccount + deploy should be bundled in one transaction.

Related to #142 batched transactions.

**Comment by mikedotexe** [comment]
Evgeny has an implementation that can be largely copied, which is great. Please see:
https://github.com/near/core-contracts/tree/master/multisig#usage
With this knowledge, let's escalate this.

**Comment by potatodepaulo** [comment]
Acceptance criteria: 
* A developer is able to deploy and init a contract in one line in either the terminal or a shell script. 
* Any developer is able to deploy and interact with their contracts with zero clicks. 
* Proper testing coverage: 
    * Separate contract with init method
    * A contract for AS and a contract for Rust
    * Automated tests for happy path

Context: 
* The code is already written, just needs to be added to shell and exposed.
* Needs new flags and thinking on UX, adding automated testing.

**Comment by evgenykuzyakov** [comment]
Here is an example of inlining `repl` within `bash`: https://github.com/near/core-contracts/blob/8cccf71f24040ce353cb3aa56e94f8d4686598c4/scripts/deploy/deploy_staking_pool_factory.sh

**Comment by mikedotexe** [comment]
little bit of progress here:
https://github.com/near/near-shell/tree/hotfix/260-deploy-init
