### ISSUE TITLE
Deploy & transfer transactions don't provide any feedback

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-shell#263]
For example:
```
near deploy --accountId=my_validator --wasmFile=res/staking_contract.wasm
```
If this command succeeded, there is no feedback that it did, or what is the transaction hash / status.

Ideally we should show transaction hash right away, with possibly a URL to explorer.
And then when transaction succeeded or failed - show that status: `adas123de12221...ok`

**Comment by potatodepaulo** [comment]
Acceptance criteria
* Expose the response in both the `transfer` and `deploy` commands
* Generate the explorer URL to the transaction on da chain

Notes
* Potentially a one line fix

**Comment by janedegtiareva** [comment]
Related issue https://github.com/near/near-shell/issues/410

**Comment by janedegtiareva** [comment]
Related issue https://github.com/near/near-shell/issues/412

**Comment by janedegtiareva** [comment]
We need to find an explorer base url for a particular network. There are several options:

- Add it to config.js. Downside is that folks with existing config files will not have this entry, so the feature wouldn't work for them. 

- static config file mapping network id to explorer url. Downside here is that devs may use custom network ids, which won't match in the static config file. 

- both, with fallback.

**Comment by mikedotexe** [comment]
I think we can add explorer links to the `config.js` (like `helperUrl`s, etc) of near-shell, and similar to other updates to this file, roll it out to the examples and other projects.
If we detect that the `explorerUrl` isn't there (with `hasOwnProperty` or something) then just output the transaction hash. If it's there, output in the normal format. (Typically `https://explorer.ENVIRONMENT.near.org/transactions/TRANSACTION_ID`)

**Comment by bowenwang1996** [comment]
I think it is a general issue that we don't provide transaction hash if the transaction succeeds. I think explorer url helps but it would also be nice to provide the hash directly so that in case explorer is down, we can still see what happens with the transaction.

**Comment by janedegtiareva** [comment]
https://github.com/near/near-shell/pull/451
