### ISSUE TITLE
Add contribution guidelines, license, code of conduct

### ISSUE THREAD

**Issue by mikedotexe** [near/near-shell#267]
Make sure all public repos have: README.md, CONTRIBUTING.md, CODE_OF_CONDUCT.md (you can take it from nearcore), LICENSE (prefer Apache, if we currently have GPL for some reason - let’s investigate why and change).
• For CONTRIBUTING - link to https://docs.nearprotocol.com/docs/contribution/contribution-overview and then add any custom information for that repo.

**Comment by janedegtiareva** [comment]
@mikedotexe can we close this?

**Comment by amgando** [comment]
closing since merged
