### ISSUE TITLE
Return link to explorer as a result for TXs

### ISSUE THREAD

**Issue by kcole16** [near/near-shell#268]
As a user, I want to view the result of my transaction (and any command that leads to a transaction) in detail, so I can understand it's current state. 

A good way to do this is to return a link to explorer for the transaction. (e.g. https://explorer.nearprotocol.com/transactions/6hed6tGezJWsRtTL43wSRDuQTxMnTPYqofFTkQ5u8tNB)

**Comment by amgando** [comment]
duplicate #283
