### ISSUE TITLE
Investigate why latest dependabot for yargs fails

### ISSUE THREAD

**Issue by mikedotexe** [near/near-shell#289]
Re-ran Travis three times and got the same failure.
It's possible there's an underlying issue in:
https://github.com/nearprotocol/near-shell/pull/285

**Comment by janedegtiareva** [comment]
The builds on that PR no longer fail. I am assuming that this had to do with assemblyscript dependency sadness that was resolved yesterday.

**Comment by janedegtiareva** [comment]
not fully true, but there are fewer failures.
