### ISSUE TITLE
Indicate to users created accounts will be subdomains

### ISSUE THREAD

**Issue by kcole16** [near/near-shell#307]
### Overview
Once https://github.com/nearprotocol/nearcore/issues/2292 lands, near-shell should indicate to users that `near create_account` can only create:
- Subdomains of the sending account `--masterAccount` 
- TLDs with >= 11 characters.

**Example:**
Using `kendall.near`, I can create accounts like `test.kendall.near` and `hasatleasteleven`.

cc @potatodepaulo @evgenykuzyakov

**Comment by bowenwang1996** [comment]
It seems that top level account names that are longer than 11 characters will still be allowed.

**Comment by ilblackdragon** [comment]
We bumping account names that are allowed to 32 characters FYI.

**Comment by mikedotexe** [comment]
I'm getting `CreateAccountNotAllowed` when I am trying this. Is this just disabled on testnet and fixed in the linked nearcore issue?

**Comment by bowenwang1996** [comment]
@mikedotexe well, `hihihihihihi.test` is unfortunately not a TLA.

**Comment by mikedotexe** [comment]
Darn, we need to reopen this and fix some issues Vlad saw this dev-deploy. My mistake for not catching it.
