### ISSUE TITLE
inspect response should supply `maxArrayLength`

### ISSUE THREAD

**Issue by DanielRX** [near/near-shell#314]
If you run a getter that returns an array of length > 100 it will return `... x more items` instead of the full array, preventing any script from using the output of `near view` as it doesn't return the entire array

**Comment by potatodepaulo** [comment]
Thanks for reporting. We're looking into this.

**Comment by janedegtiareva** [comment]
Fix here https://github.com/near/near-shell/pull/366
This will be available soon in the next shell version.
