### ISSUE TITLE
near repl is not working

### ISSUE THREAD

**Issue by janedegtiareva** [near/near-shell#325]
C:\Users\janed\near\near-shell>node bin\near repl
near repl

launch interactive Node.js shell with NEAR connection available to use

Options:
  --help                     Show help  [boolean]
  --version                  Show version number  [boolean]
  --nodeUrl, --node_url      NEAR node URL  [string] [default: "http://localhost:3030"]
  --networkId, --network_id  NEAR network ID, allows using different keys based on network  [string] [default: "default"]
  --helperUrl                NEAR contract helper URL  [string]
  --keyPath                  Path to master account key  [string]
  --accountId, --account_id  Unique identifier for the account  [string]

Unknown argument: respawning

**Comment by evgenykuzyakov** [comment]
Still doesn't work.

**Comment by janedegtiareva** [comment]
I spent a tiny amount of time investigating the error. 
If we print out the command line arguments on near repl, here's the output: 
`[
  'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\janed\\near\\near-shell\\bin\\near',
  'repl',
  '--no-respawning'
]`

I am not sure where the --no-respawning flag gets added and why this is not happening for other commands.

**Comment by janedegtiareva** [comment]
Fixed here https://github.com/near/near-shell/commit/25e75cb53a61f81c85f3b1cc93fda4fb42f0e09e
