### ISSUE TITLE
Ownership of `near-cli` package

### ISSUE THREAD

**Issue by gokaygurcan** [near/near-shell#329]
Hi guys,

Today, I received an email from @potatodepaulo, about the ownership of near-cli package on npm. It was for a project I started ~5 years ago that uses Node, Express, Angular and RethinkDB (hence the name), but Angular went crazy and I never completed the project. So, feel free to use it if you want.

I just unpublished `near-cli@0.0.0` before handing it over to you, I think it's up for grab now. 

Be quick :)

Best,
G.

**Comment by potatodepaulo** [comment]
Thanks!

**Comment by potatodepaulo** [comment]
Looks like we need to wait 24 hours before we can take ownership.

**Comment by gokaygurcan** [comment]
Looks like you claimed `near-cli` already. It was unlucky to start with v1.0.0 but you can always unpublish it. 

You can close the issue whenever you want, I think I have nothing else to do here :)
