### ISSUE TITLE
Can't delete access keys

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/near-shell#353]
Seems `near-shell` doesn't support deletion of the access keys.
It doesn't allow create keyless contracts.

**Comment by janedegtiareva** [comment]
We can add it. What is the RPC call that needs to happen?

**Comment by evgenykuzyakov** [comment]
It's `DeleteKey` action. As here: https://github.com/near/near-api-js/blob/9ffd92ed02cf4128df8428e7350662697a767b89/src/account.ts#L264

**Comment by mikedotexe** [comment]
Seems like this is getting more important as we get to Stake Wars, think we should change the label of "enhancement"?

**Comment by potatodepaulo** [comment]
Clarifying from discussion:
`near delete <PubKey>` will allow you to use the full access key to delete any key.

**Comment by mikedotexe** [comment]
fixed here: https://github.com/near/near-shell/pull/383
although I guess that's already appearing in "Linked pull requests" in the right sidebar. I'll use that from now on.
