### ISSUE TITLE
"near login" auto-opens wrong Wallet link on Linux

### ISSUE THREAD

**Issue by mikedotexe** [near/near-shell#358]
There have been a number of folks who have tried using the command "near login" and have seen a red banner at the top. It appears two folks have been on Ubuntu and seen this.
I've installed VMs of three version of Ubuntu and can't seem to reproduce it, but I can reproduce this in Gitpod.

Steps to reproduce: open up a Gitpod instance. (from an example from [near.dev](https://near.dev), for instance) and in the Terminal run `near login` **twice**

The second time, you'll note that the URL that automatically opens in the browser tab has a different public key than the link in the command line. I've spent enough time trying to track this down, that I'm considering this an exotic bug and it's deprioritized. It was a cherry-on-top feature to begin with, and it's unfortunately blocking a lot of our users.

Here are three different cases where this has happened in the past week, screenshots from Slack:
<img width="389" alt="Screenshot 2020-05-08 10 37 38" src="https://user-images.githubusercontent.com/1042667/81432792-62bcbb80-9118-11ea-9af5-33a9b5ea7d46.png">
<img width="327" alt="Screenshot 2020-05-08 10 37 15" src="https://user-images.githubusercontent.com/1042667/81432799-65b7ac00-9118-11ea-8e22-2425c5ce4a5e.png">
<img width="323" alt="Screenshot 2020-05-08 10 36 44" src="https://user-images.githubusercontent.com/1042667/81432805-681a0600-9118-11ea-869b-08fc6c8e3058.png">

**Comment by vgrichina** [comment]
@mikedotexe I cannot reproduce this on GitPod. Can you give more details on how to reproduce?

I think we shouldn't be disabling this flow for GitPod.

**Comment by vgrichina** [comment]
Note that examples need to include this in config for smoother flow:
https://github.com/near/near-shell/blob/7e3f8b1dad129439ab7eb9ba811d659b3042ecfa/.gitpod.yml#L7

**Comment by mikedotexe** [comment]
@vgrichina just to make sure, what was your steps to reproduce? As you see I merged #361 so by default, Gitpod's `master` will work as expected, except you have to enter your id in the terminal.
I followed this procedure to reproduce on Brave and Chrome.

1. Visit: https://github.com/near/near-shell
2. open Gitpod in new tab
3. In the Gitpod Terminal go back to before the merge with:
4. `git checkout 779fab0158c20e0932d3527c33fde2a7b5756bca`
5. Then run `./bin/near login`
6. Follow instructions
7. See that it worked
8. Run `./bin/near login` again
9. Follow instructions again
10. See that the red banner appears in Wall

et, but it's because of an issue in shell.

**Comment by vgrichina** [comment]
@mikedotexe  I did exactly the steps you gave in issue description (these didn't involve using version from GitHub `master`):

> Steps to reproduce: open up a Gitpod instance. (from an example from near.dev, for instance) and in the Terminal run near login twice

I think in your updated steps "Follow instructions" can go very different ways:
1) your browser can open popup automatically or block it.
2) you can press a link in terminal yourself
3) you can press "Open browser" in dialog box popped by GitPod.

So which one did you use when reproducing?

**Comment by vgrichina** [comment]
Ok, was able to get this in Chrome when following new directions:

> The account you provided [ test1.testnet ] has not authorized the expected key [ ed25519:29tcYw... ]  Please try again.

**Comment by mikedotexe** [comment]
That's true that "follow instructions" is vague, I use "open browser" from the dialog. 
>2. you can press a link in terminal yourself
The entire issue is that you *can* press the link from Terminal and it'll work every time. Any other method will fail on the second time on certain linux distros. I think this is really odd caching or something. I believe it might be the 301 inside the handler from the payload call. But I spent enough time spinning my wheels on this, and want to unblock our users.

**Comment by mikedotexe** [comment]
this is the most important part of the PR description:
> the URL that automatically opens in the browser tab has a different public key than the link in the command line

**Comment by vgrichina** [comment]
@mikedotexe fixed here https://github.com/near/near-shell/pull/363

**Comment by vgrichina** [comment]
> I believe it might be the 301 inside the handler from the payload call. 

it was indeed 301 instead of 302
