### ISSUE TITLE
view call doesn't work on betanet

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-shell#371]
On betanet, because the account `register.near` doesn't exist, a view call will fail if `--accountId` is not specified. The reason is this line will default to use `register.near` if no account is specified and the user hasn't logged in yet. https://github.com/near/near-shell/blob/95c0c5e33fb5af9d9f319a00858c4a0759c50c2c/index.js#L51 While it is easy to fix this by creating `register.near`, I think we shouldn't rely on the existence of some account on every network. Furthermore, there is no reason that an account id has to be provided here. It seems rather an issue with how API is structured in near-api-js (I am not quite sure why viewFunction has to be a method on account).

**Comment by bowenwang1996** [comment]
To reproduce, try the following with `NODE_ENV=betanet`:
```
near view unknown.test get_owner_id '{}'
```

**Comment by vgrichina** [comment]
```
[I] ➜ NODE_ENV=betanet bin/near view unknown.test get_owner_id '{}'
Using options: {
  networkId: 'betanet',
  nodeUrl: 'https://rpc.betanet.near.org',
  contractName: 'unknown.test',
  walletUrl: 'https://wallet.betanet.near.org',
  helperUrl: 'https://helper.betanet.near.org',
  methodName: 'get_owner_id',
  args: '{}',
  initialBalance: null
}
View call: unknown.test.get_owner_id({})
'rich-guy.betanet'
```

@bowenwang1996 looks like fix works fine
