### ISSUE TITLE
near login doesn't work

### ISSUE THREAD

**Issue by AlexDCryptoC** [near/near-shell#381]
Hei guys.,

For me near login doesn't work and this command brings me the following error. P.S: i export NODE_ENV=betanet and added in bash, also i reopened terminal. My node vers: 13.5.0, npm: 6.14.5 
![near login](https://user-images.githubusercontent.com/18679675/82557634-bdbccc80-9b74-11ea-8217-c689dbd60a05.jpg)

**Comment by potatodepaulo** [comment]
@AlexDCryptoC thanks for submitting. I think the solution might be for us to make the node version requirements more clear.
