### ISSUE TITLE
Package libusb-1.0 was not found

### ISSUE THREAD

**Issue by frol** [near/near-shell#384]
Since the last release near-shell requires system package libusb (dev / devel version with headers) and fails to install:

```
# npm install -g near-shell --unsafe-perm
/usr/local/bin/near -> /usr/local/lib/node_modules/near-shell/bin/near

> node-hid@1.2.0 install /usr/local/lib/node_modules/near-shell/node_modules/node-hid
> prebuild-install || node-gyp rebuild

prebuild-install WARN install /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/lib/node_modules/near-shell/node_modules/node-hid/build/Release/HID.node)
Package libusb-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libusb-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libusb-1.0' found
gyp: Call to 'pkg-config libusb-1.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 3.10.0-1062.4.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/near-shell/node_modules/node-hid
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@1.2.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hid@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-22T15_24_41_141Z-debug.log
```

Can we make USB support opt-in?

I wonder if I should have used P0 here since near-shell is not installable for some users now.

**Comment by zavodil** [comment]
I just installed yum install libusbx-devel and now see the following:

`npm install -g near-shell --unsafe-perm
/usr/local/bin/near -> /usr/local/lib/node_modules/near-shell/bin/near

> node-hid@1.2.0 install /usr/local/lib/node_modules/near-shell/node_modules/node-hid
> prebuild-install || node-gyp rebuild

prebuild-install WARN install /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/lib/node_modules/near-shell/node_modules/node-hid/build/Release/HID.node)
make: Entering directory `/usr/local/lib/node_modules/near-shell/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi-linux-hidraw/hidapi/linux/hid.o
../hidapi/linux/hid.c:44:21: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
                     ^
compilation terminated.
make: *** [Release/obj.target/hidapi-linux-hidraw/hidapi/linux/hid.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/near-shell/node_modules/node-hid/build'
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 3.10.0-1062.4.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/near-shell/node_modules/node-hid
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@1.2.0 install: prebuild-install || node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hid@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-22T15_31_59_550Z-debug.log`

**Comment by frol** [comment]
yeah, that means that not only libusb-dev, but also libudev-dev is necessary. We are getting deeper into the rabbit hole

**Comment by zavodil** [comment]
Confirned. with yum install libudev-devel its fine

**Comment by frol** [comment]
@zavodil Do you still need `--unsafe-perm`?

**Comment by zavodil** [comment]
nope

 npm install -g near-shell
/usr/local/bin/near -> /usr/local/lib/node_modules/near-shell/bin/near
+ near-shell@0.24.0
updated 1 package in 11.112s

**Comment by frol** [comment]
To sum up, on CentOS you need:

```
$ sudo yum install libusbx-devel libudev-devel
```

On Ubuntu:

```
$ sudo apt install libusb-dev libudev-dev
```

Still, users report issues:

![image](https://user-images.githubusercontent.com/304265/82708149-f5e70c80-9c53-11ea-80ab-bf12124aec9f.png)

```
Failed to initialize libusb.
```

https://t.me/near_protocol/4540

**Comment by vgrichina** [comment]
Fixed in https://github.com/near/near-shell/releases/tag/v0.24.1

Note that error will still show up but not fail install.

**Comment by jilt** [comment]
so I'm ignoring the error right?
