### ISSUE TITLE
Output explorer link for any successful transaction

### ISSUE THREAD

**Issue by eriktrautman** [near/near-shell#410]
For usability, it'd be very helpful if any confirmed transaction from the CLI outputs the tx ID with a helpful link to the explorer where it can be viewed.

**Comment by evgenykuzyakov** [comment]
Moved to near-shell

**Comment by evgenykuzyakov** [comment]
I'd also suggest to output explorer link for unsuccessful transactions. Because if the RPC node times out, it still possible that the TX was accepted.

**Comment by janedegtiareva** [comment]
Printing txn id/ explorer link for failed txns requires near-api-js changes and makes this effort at least 5 story points.

**Comment by janedegtiareva** [comment]
Let's make a different issue for printing it for errors, since it's more complex and requires near-api-js changes.

**Comment by janedegtiareva** [comment]
https://github.com/near/near-shell/pull/463
https://github.com/near/near-api-js/pull/362
