### ISSUE TITLE
Create account error handling on a sharded network

### ISSUE THREAD

**Issue by htafolla** [near/near-shell#439]
Create account via `near` shell on a sharded node returns server timeout instead of the error.

COMMAND:

    near create-account c1.nearcat.guildnet --nodeUrl=http://161.35.229.231:3030/ --helperAccount guildnet --networkId guildnet --helperUrl http://164.90.144.140:3000/ --masterAccount nearcat.guildnet

RETURNS:

    Error:  TypedError: [-32000] Server error: Timeout error...

MESSAGE ON VALIDATOR:

    WARN network: Received invalid tx from peer Sender "blaze3.guildnet" does not have enough balance 10000000000000000000000000 for operation costing 100000000086184677687500000

**Comment by chadoh** [comment]
@vgrichina @mikedotexe is this something that one of you know about off the top of your head?

**Comment by mikedotexe** [comment]
Thanks for reporting @htafolla ! I believe the underlying solution is this PR which I will try to complete very soon:
https://github.com/near/near-shell/pull/402

I think I will close this in favor of the solution that handles timeouts appropriately.
Thanks again!
