### ISSUE TITLE
Some calls receive "Transaction Id null" 

### ISSUE THREAD

**Issue by mikedotexe** [near/near-shell#466]
**Describe the bug**
A Discord user noticed that a particular call on betanet doesn't return the transaction ID. We'll want to investigate and fix. Perhaps it's a betanet issue, or something that needs to change in the way we parse transactions.

**To Reproduce**
`NEAR_ENV=betanet near call paulainsley1betanet.stakehouse.betanet ping '{}' --accountId YOU.betanet`

**Expected behavior**
The transaction ID is retrieved, or if it's impossible, a message other than "Transaction ID null" is shown to the user.

**Screenshots**
<img width="1137" alt="Screenshot 2020-07-22 07 45 43" src="https://user-images.githubusercontent.com/1042667/88190633-5ca28b00-cbef-11ea-8ada-8c65666a70ae.png">

**Comment by youlaiwuqu** [comment]
1.near call stakingpool.youlaiwuqu.betanet ping '{}' --accountId youlaiwuqu.betanet
Scheduling a call: stakingpool.youlaiwuqu.betanet.ping({})
Retrying transaction youlaiwuqu.betanet:5g84npvqG2MWXganPEtbzoyv7AkhBMb6LteHvY2FkxtC as it has timed out
Receipts: 4NFDapehW2VNB8CC9dgHsMJKndBDjGFe3EFRt23121Jc, 3oDTxPCmbgGSiekaHmM9NteESg8Jf66m4LMLYLAt5DiL
        Log [stakingpool.youlaiwuqu.betanet]: Epoch 101: Contract received total rewards of 190177553414070713483281743 tokens. New total staked balance is 151230141431257489953242600912. Total number of shares 150787116975840348384100671599
        Log [stakingpool.youlaiwuqu.betanet]: Total rewards fee is 18962043360821421467103637 stake shares.
Transaction Id null
2. near call stakingpool.youlaiwuqu.betanet ping '{}' --accountId youlaiwuqu.betanet
Scheduling a call: stakingpool.youlaiwuqu.betanet.ping({})
Transaction Id null
The screenshot is below:
http://chuantu.xyz/t6/739/1595430261x1700339730.png

**Comment by mikedotexe** [comment]
Thank you for the thorough steps @youlaiwuqu !

**Comment by janedegtiareva** [comment]
https://github.com/near/near-shell/pull/471
