### ISSUE TITLE
near shell fails silently and unhelpfully in case command is not recognized

### ISSUE THREAD

**Issue by janedegtiareva** [near/near-shell#50]
steps to repro:
near blahblah 
outputs nothing

instead, should say something about unrecognized command. 

This used to work before

**Comment by potatodepaulo** [comment]
Expected behavior:

```bash
near not_a_command

output:
[all the help docs]

```

**Comment by vgrichina** [comment]
@potatodepaulo this has a fix https://github.com/nearprotocol/near-shell/pull/51 but we'll need to change how config is loaded. Otherwise extra options in config will cause failures.

**Comment by kcole16** [comment]
Now getting this when typing `near not_a_command`

```
[WARNING] Didn't find config at /Users/kendallcole/Desktop/near/src/config, using default shell config
{
  networkId: 'default',
  nodeUrl: 'https://rpc.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.nearprotocol.com'
}
```

**Comment by mikedotexe** [comment]
Also related to issue Illia created:
https://github.com/nearprotocol/near-shell/issues/259

There are a links that address this issue and I've done work to find a happy medium.

@potatodepaulo mentioned it would be nice to have the options when you enter an invalid command. My approach will tell the user what command was invalid very tersely and obviously to the end user. They can type `near` or `near --help` to see the full list of commands.
In terms of what @kcole16 mentioned, I think we'll want to keep that, but it'll be above the more helpful errors informing the user of their incorrect usage.

![Screenshot 2020-02-05 11.01.17.png](https://images.zenhubusercontent.com/5a60db2a4b5806bc2bc34af6/181736c1-c4f3-46dc-b97e-960025463116)

This ended up being a rather interesting problem. Please see my pull request here which is ready for review:
https://github.com/nearprotocol/near-shell/pull/262
(PS - I'm not sure why Travis is failing, but I don't believe it's something in the PR)
